### ISSUE TITLE
Feature Request: Changing the size of the gantt (e.g. zoom out) on long time periods

### ISSUE THREAD

**Issue by PifPof73** [cosmocode/dokuwiki-plugin-structgantt#10]
Hi,
on long time scales, the gantt is getting quite long.
To enable a good overview it would be nice to either

- [ ] be able to change the size and therefor shrink weeks to daysize (for example)
or
- [ ] be able to shorten a long running bar by interrupting it by displaying only the beginning date and some weeks and than some weeks and the ending date like 

```
April 2019         | ... | Dec 2019
MTWTFMTWTFM        | ... | MTWTFMTW
[project xy begin  | ... | project end] 
```

Greetings,
PifPof73

**Comment by jpvalois** [comment]
Hello,

I could not agree more with PifPof73's comment. Long graphs that span many years are hard to figure out. I'd love a way to zoom in/out, or a way to configure what the smallest time period shown will be (day, week, month, quarter, semester, year).

Thanks!
jp

**Comment by splitbrain** [comment]
Some autoscaling for long periods has been implemented. Interactive scaling is out of scope for this plugin.
