### ISSUE TITLE
Time Scale Does not Fit

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-structgantt#6]
I am using the plugin for a three year project plan with 50 workpackages. Documentation says, that: "The chart automatically switches the headers from days, week numbers and month names depending on the amount of days in the whole chart"
In my huge chart are only months and days (see screenshot). I would like to see years, months and weeks, but not single days... 
And there is an error too: As you can see in the screenshot, today (2018-01-05) is in September.
![grafik](https://user-images.githubusercontent.com/2620833/34616196-bb68477c-f237-11e7-87fb-9ea54a64e3c9.png)

**Comment by splitbrain** [comment]
Yes, the plugin only changes the headers accordingly. It is always based on days.

**Comment by stvoigt** [comment]
Okay. Should I open an extra issue for the error? (2018-01-05 != in September)

**Comment by splitbrain** [comment]
Oh, yeah that's weird indeed. new ticket please.
