### ISSUE TITLE
Feature Request: Display Year in large time scale

### ISSUE THREAD

**Issue by PifPof73** [cosmocode/dokuwiki-plugin-structgantt#9]
Hi,
on long term projects, the gantt is missing the year information at the month scale.

Would it be possible to change line 229 in gantt.php from:
`            $format = 'F'; // months`
to show also the years after each month to:
`            $format = 'F Y'; // months and year`

Or - even better- do an config switch "showYears".
Greetings,
PifPof73

**Comment by jpvalois** [comment]
Hello,

I feel this would be useful as well.

In fact, individual switches of type "show/noshow/auto" for "year", "quarter", "month", "week" and "day" would be much appreciated. For my use, I almost never need to show days, so having a way to disable days would make more sense and would mostly make the chart much more compact.

Best,
jp

**Comment by splitbrain** [comment]
this has been implemented
